var pungleJSON = 
{ "store": [
	{
		"id": 78,
		"tags": [9],
		"name": "1-800 Baskets",
		"domain": "",
		"desc": "Gourmet gift baskets and food gifts for every occasion.",
		"link": "http://click.linksynergy.com/fs-bin/click?id=GU*lP9Glm/0&offerid=185580.10000001&type=4&subid=0",
		"img": "1800baskets.png",
		"aff": true,
		"live": true
	},
	{
		"id": 77,
		"tags": [9],
		"name": "1-800 Flowers",
    "domain": "",
		"desc": "Order flowers, roses, gift baskets and more. Get same-day flower delivery for birthdays, anniversaries, and all other occasions.",
		"link": "http://click.linksynergy.com/fs-bin/click?id=GU*lP9Glm/0&offerid=100462.10000286&type=3&subid=0",
		"img": "1800flowers.png",
		"aff": true,
		"live": true
	},
	{
		"id": 85,
		"tags": [5],
		"name": "123 Inkjets",
    "domain": "",
		"desc": "A top supplier of discount ink cartridges and toner for nearly every model of inkjet and laser printer on the market today.",
		"link": "http://www.dpbolvw.net/click-4147908-10790382",
		"img": "123inkjets.png",
		"aff": true,
		"live": true
	},
	{
		"id": 62,
		"tags": [2],
		"name": "4 Wheel Parts",
    "domain": "",
		"desc": "Serving the needs off-road enthusiasts for over 40 years as the nations largest distributor of 4x4 parts and accessories for trucks, Jeeps, and SUV's.",
		"link": "http://www.tkqlhce.com/click-4147908-10458480",
		"img": "4wheelparts.png",
		"aff": true,
		"live": true
	},
	{
		"id": 84,
		"tags": [1,4],
		"name": "6pm.com",
    "domain": "",
		"desc": "Get more for your dollar when you shop shoes, clothes, and bags on 6pm.com. Save up to 75% off retail prices when you explore our amazing deals.",
		"link": "http://www.jdoqocy.com/click-4147908-10812805",
		"img": "6pm.png",
		"aff": true,
		"live": true
	},
	{
		"id": 27,
		"tags": [1,4,17],
		"name": "Adidas",
    "domain": "",
		"desc": "See the latest adidas for running, basketball, soccer and more. Explore style collections from adidas Originals and Y-3.",
		"link": "http://www.jdoqocy.com/click-4147908-10440391",
		"img": "adidas.png",
		"aff": true,
		"live": true		
	},
	{
		"id": 83,
		"tags": [2],
		"name": "Advance Auto Parts",
    "domain": "",
		"desc": "Your source for quality auto parts, advice and accessories. Shop online for home delivery or pick up at a location near you.",
		"link": "http://www.anrdoezrs.net/click-4147908-10804489",
		"img": "advanceautoparts.png",
		"aff": true,
		"live": true		
	},
	{
		"id": 63,
		"tags": [5],
		"name": "Adobe",
    "domain": "",
		"desc": "Innovators for digital media creation and editing, multimedia authoring, and web development.",
		"link": "http://www.jdoqocy.com/click-4147908-10453550",
		"img": "adobe.png",
		"aff": true,
		"live": true
	},
	{
		"id": 126,
		"tags": [1,4,17],
		"name": "Aeropostale",
    "domain": "",
		"desc": "Focused selection of high-quality, active-oriented, fashion and fashion basic merchandise.",
		"link": "http://www.aeropostale.com",
		"img": ".png",
		"aff": false,
		"live": false
	},
	{
		"id": 86,
		"tags": [20,9,8],
		"name": "All Posters",
    "domain": "",
		"desc": "With more than 900,000 images, AllPosters is your one-stop-shop for wall art.",
		"link": "http://www.kqzyfj.com/click-4147908-10770696",
		"img": "allposters.png",
		"aff": true,
		"live": true		
	},
	{
		"id": 64,
		"tags": [1],
		"name": "Allen Edmonds",
    "domain": "",
		"desc": "The official site of the world's leading manufacturer of quality leather mens shoes.",
		"link": "http://gan.doubleclick.net/gan_click?lid=41000000031472139&pubid=21000000000316594",
		"img": "allenedmonds.png",
		"aff": true,
		"live": true		
	},
	{
		"id": 111,
		"tags": [1,4],
		"name": "Alternative Apparel",
    "domain": "",
		"desc": "Premier casual lifestyle apparel brand, delivering the best quality and value in fashion basics.",
		"link": "http://gan.doubleclick.net/gan_click?lid=41000000029026066&pubid=21000000000316594",
		"img": "alternativeapparel.png",
		"aff": true,
		"live": true
	},
	{
		"id": 0,
		"tags": [1,2,3,4,5,6,7,8,9,10,11,13,14,15,16,17],
		"name": "Amazon",
		"domain": "amazon.com",
		"desc": "The earth's biggest selection of books, magazines, music, DVDs, videos, electronics, computers, software, apparel & just about anything else.",
		"link": "http://www.amazon.com/gp/redirect.html?ie=UTF8&location=http%3A%2F%2Fwww.amazon.com%2F&tag=pungle00-20&linkCode=ur2&camp=1789&creative=390957",
		"img": "amazon.png",
		"aff": true,
		"live": true
	},
	{
		"id": 112,
		"tags": [1,4,7],
		"name": "American Apparel",
    "domain": "",
		"desc": "Fashionable basics. Sweatshop free. Made in USA. That's American Apparel.",
		"link": "http://www.amazon.com/gp/redirect.html?ie=UTF8&location=http%3A%2F%2Fwww.amazon.com%2Fgp%2Fentity%2FAmerican-Apparel%2F2491485011%3Fie%3DUTF8%26ref_%3Dep_sprkl_br_2491485011&tag=pungle00-20&linkCode=ur2&camp=1789&creative=390957",
		"img": "americanapparel.png",
		"aff": true,
		"live": true
	},
	{
		"id": 128,
		"tags": [1,4,7,9,11],
		"name": "Anthropologie",
    "domain": "",
		"desc": "An inspiring place to shop for Women's clothing, accessories, and home decor.",
		"link": "http://www.anthropologie.com",
		"img": "anthropologie.png",
		"aff": false,
		"live": true
	},
	{
		"id": 129,
		"tags": [5,6],
		"name": "Apple Store",
    "domain": "",
		"desc": "Experience the wide world of Apple at the Apple Store.",
		"link": "http://store.apple.com/us",
		"img": "apple.png",
		"aff": false,
		"live": true
	},
	{
		"id": 154,
		"tags": [1,4,17],
		"name": "Athleta",
    "domain": "",
		"desc": "Women's yoga clothing, swimwear, running clothing and athletic clothing for fitness, golf & tennis.",
		"link": "http://www.kqzyfj.com/click-4147908-10415271",
		"img": "athleta.png",
		"aff": true,
		"live": true
	},
	{
		"id": 155,
		"tags": [3,13],
		"name": "Audible",
    "domain": "",
		"desc": "Download audio books for your ipod or MP3 player.",
		"link": "http://www.jdoqocy.com/click-4147908-10298646",
		"img": "audible.png",
		"aff": true,
		"live": true
	},
	{
		"id": 65,
		"tags": [2],
		"name": "Auto Parts Warehouse",
    "domain": "",
		"desc": "Online retailer offering replacement parts, performance parts and auto accessories at wholesale prices.",
		"link": "http://www.anrdoezrs.net/click-4147908-1058847",
		"img": "autopartswarehouse.png",
		"aff": true,
		"live": true
	},
	{
		"id": 131,
		"tags": [20,6],
		"name": "B&H Photo",
    "domain": "",
		"desc": "Photographic and consumer electronics, including new and used equipment.",
		"link": "http://www.bhphotovideo.com/",
		"img": "bhphoto.png",
		"aff": false,
		"live": true
	},
	{
		"id": 122,
		"tags": [4,17],
		"name": "Backcountry.com",
    "domain": "",
		"desc": "The foremost selection of The North Face, Mountain Hardwear, Arc'teryx, and Patagonia skiing, camping, hiking, and backpacking gear.",
		"link": "http://www.backcountry.com/",
		"img": ".png",
		"aff": false,
		"live": false
	},
	{
		"id": 152,
		"tags": [1,4],
		"name": "Banana Republic",
    "domain": "",
		"desc": "Modern, refined clothing for men and women, plus shoes and accessories.",
		"link": "http://www.kqzyfj.com/click-4147908-10415271",
		"img": "bananarepublic.png",
		"aff": true,
		"live": true
	},
	{
		"id": 41,
		"tags": [3,13,8],
		"name": "Barnes & Noble",
    "domain": "",
		"desc": "Books, DVDs, Music, Toys & Games and More.",
		"link": "http://click.linksynergy.com/fs-bin/click?id=GU*lP9Glm/0&offerid=229293.54&type=3&subid=0",
		"img": "barnesandnoble.png",
		"aff": true,
		"live": true
	},
	{
		"id": 163,
		"tags": [1,4,10],
		"name": "BCBG",
    "domain": "",
		"desc": "Suits, separates, jeans, coats, dresses, hangbags and fragrance products.",
		"link": "http://www.bcbg.com",
		"img": "bcbg.png",
		"aff": false,
		"live": true
	},
	{
		"id": 39,
		"tags": [1,4],
		"name": "Bebe",
    "domain": "",
		"desc": "Women's sexy & trendy clothing, dresses, tops, shoes, jeans, handbags and accessories.",
		"link": "http://gan.doubleclick.net/gan_click?lid=41000225506595267&pubid=21000000000316594",
		"img": "bebe.png",
		"aff": true,
		"live": true
	},
	{
		"id": 130,
		"tags": [7,9,11],
		"name": "Bed Bath & Beyond",
    "domain": "",
		"desc": "Bedding, bath towels, kitchen electrics, cookware, window treatments, storage items, gifts and much more.",
		"link": "http://www.bedbathandbeyond.com",
		"img": "bedbathandbeyond.png",
		"aff": false,
		"live": true
	},
	{
		"id": 8,
		"tags": [5,6,13,15,14],
		"name": "Best Buy",
    "domain": "",
		"desc": "Retailer of consumer electronics and entertainment software Electronics, Appliances, Cell Phones, CDs, DVDs & More.",
		"link": "http://www.kqzyfj.com/click-4147908-10482812",
		"img": "bestbuy.png",
		"aff": true,
		"live": true
	},
	{
		"id": 66,
		"tags": [1],
		"name": "Blue Nile",
    "domain": "",
		"desc": "Largest online retailer of certified diamonds, engagement rings and fine jewelry.  Build your engagement ring online.",
		"link": "http://gan.doubleclick.net/gan_click?lid=41000000027176530&pubid=21000000000316594",
		"img": "bluenile.png",
		"aff": true,
		"live": true
	},
	{
		"id": 124,
		"tags": [1,4],
		"name": "Bluefly",
    "domain": "",
		"desc": "Designer clothing, handbags, shoes, and accessories at discount prices.",
		"link": "http://www.bluefly.com",
		"img": "bluefly.png",
		"aff": false,
		"live": true
	},
	{
		"id": 37,
		"tags": [9,10],
		"name": "The Body Shop",
    "domain": "",
		"desc": "Natural beauty products including natural skin care, make-up, body butter, aromatherapy, hair care and more.",
		"link": "http://click.linksynergy.com/fs-bin/click?id=GU*lP9Glm/0&offerid=97526.10001495&type=4&subid=0",
		"img": "bodyshop.png",
		"aff": true,
		"live": true
	},
	{
		"id": 40,
		"tags": [3,8,13],
		"name": "Borders",
    "domain": "",
		"desc": "Books, music, DVDs, Blu-ray, gifts, toys & games.",
		"link": "http://www.dpbolvw.net/click-4147908-10568661?cm_mmc=CJ-_-3149226-_-4147908-_-88x31%20logo",
		"img": "borders.png",
		"aff": true,
		"live": true
	},
	{
		"id": 179,
		"tags": [1,4,9,10,11,16],
		"name": "Boscov's",
    "domain": "",
		"desc": "Latest styles and trends in fashion and home decor.",
		"link": "http://www.boscovs.com",
		"img": "boscovs.png",
		"aff": false,
		"live": true
	},
	{
		"id": 132,
		"tags": [1,4],
		"name": "BTC Elements",
    "domain": "",
		"desc": "Fresh, inspiring fashion designs that are both earth friendly and ethically sourced.",
		"link": "http://www.btcelements.com",
		"img": "btcelements.png",
		"aff": false,
		"live": true
	},
	{
		"id": 21,
		"tags": [18],
		"name": "Budget",
    "domain": "",
		"desc": "Car rentals including sedans, trucks, SUV's and more.",
		"link": "http://www.kqzyfj.com/click-4147908-10431575",
		"img": "budget.png",
		"aff": true,
		"live": true
	},
	{
		"id": 67,
		"tags": [4],
		"name": "Busted Tees",
    "domain": "",
		"desc": "Funny t-shirts on American Apparel, hip t-shirt designs and retro vintage styles.",
		"link": "http://www.tkqlhce.com/click-4147908-10406619",
		"img": "bustedtees.png",
		"aff": true,
		"live": true
	},
	{
		"id": 17,
		"tags": [1,20,3,4,5,6,7,8,10,11,13,14,15,16,17,19],
		"name": "Buy.com",
    "domain": "",
		"desc": "Low Prices on 8 Million+ Items",
		"link": "http://affiliate.buy.com/fs-bin/click?id=GU*lP9Glm/0&offerid=212696.10000236&type=3&subid=0",
		"img": "buy.png",
		"aff": true,
		"live": true
	},
	{
		"id": 161,
		"tags": [1,4,17],
		"name": "Cache",
    "domain": "",
		"desc": "Distinctive casual sportswear to stunning eveningwear to contemporary accessories.",
		"link": "http://www.cache.com",
		"img": "cache.png",
		"aff": false,
		"live": true
	},
	{
		"id": 87,
		"tags": [7,9],
		"name": "Celebrate Express",
    "domain": "",
		"desc": "Ultimate resource for party supplies.",
		"link": "http://www.tkqlhce.com/click-4147908-10641229",
		"img": "celebrateexpress.png",
		"aff": true,
		"live": true,
		"deals": [
		]
	},
	{
		"id": 164,
		"tags": [1,4,7],
		"name": "Chloe Loves Charlie",
    "domain": "",
		"desc": "Affordable, trendy Juniors fashion from emerging designers and labels.",
		"link": "http://www.chloelovescharlie.com",
		"img": "chloelovescharlie.png",
		"aff": false,
		"live": true
	},
	{
		"id": 149,
		"tags": [9,11,19],
		"name": "Cost Plus World Market",
    "domain": "worldmarket.com",
		"desc": "Unique and authentic home furnishings, decor and more.",
		"link": "http://www.worldmarket.com",
		"img": ".png",
		"aff": false,
		"live": false
	},
	{
		"id": 88,
		"tags": [5,6],
		"name": "Dell Home",
    "domain": "",
		"desc": "Dell desktop or laptop home computers and electronics for your home or small office.",
		"link": "http://www.jdoqocy.com/click-4147908-10494080",
		"img": "dell.png",
		"aff": true,
		"live": true
	},
	{
		"id": 160,
		"tags": [11],
		"name": "Design Within Reach",
    "domain": "",
		"desc": "Enduring, purposeful and innovative furniture and accessories.",
		"link": "http://www.dwr.com",
		"img": "designwithinreach.png",
		"aff": false,
		"live": true
	},
	{
		"id": 22,
		"tags": [17],
		"name": "Dick's Sporting Goods",
    "domain": "",
		"desc": "Shop Dick's Sporting Goods for the finest quality products at competitive prices, backed by the best service anywhere.",
		"link": "http://www.pjtra.com/t/Sj9GRkZHP0dLSUdLP0ZIR0ZC",
		"img": "dickssportinggoods.png",
		"aff": true,
		"live": true
	},
	{
		"id": 89,
		"tags": [20,7],
		"name": "Discount School Supply",
    "domain": "",
		"desc": "Lowest prices on school supplies and equipment for early childhood educators, caregivers and parents of young children.",
		"link": "http://www.dpbolvw.net/click-4147908-10665101",
		"img": "discountschoolsupply.png",
		"aff": true,
		"live": true
	},
	{
		"id": 90,
		"tags": [7,9],
		"name": "Disney Store",
    "domain": "",
		"desc": "The official site for Disney merchandise.",
		"link": "http://www.tkqlhce.com/click-4147908-10682890",
		"img": "disney.png",
		"aff": true,
		"live": true
	},
	{
		"id": 123,
		"tags": [17],
		"name": "Dogfunk",
    "domain": "",
		"desc": "Park and powder snowboarding gear.",
		"link": "http://www.dogfunk.com",
		"img": ".png",
		"aff": false,
		"live": false
	},
	{
		"id": 68,
		"tags": [10,11],
		"name": "Drugstore.com",
    "domain": "drugstore.com",
		"desc": "Online pharmacy for prescription drugs and information as well as health, beauty, green & natural products, household items & much more.",
		"link": "http://click.linksynergy.com/fs-bin/click?id=GU*lP9Glm/0&offerid=215687.10000553&type=4&subid=0",
		"img": "drugstore.png",
		"aff": true,
		"live": true
	},
	{
		"id": 99,
		"tags": [1,17],
		"name": "Eastbay",
    "domain": "",
		"desc": "Largest selection of brands, colors & sizes of athletic shoes for sports & casual shoes for play.",
		"link": "http://click.linksynergy.com/fs-bin/click?id=GU*lP9Glm/0&offerid=203805.10000005&type=3&subid=0",
		"img": "eastbay.png",
		"aff": true,
		"live": true
	},
	{
		"id": 100,
		"tags": [14],
		"name": "EB Games",
    "domain": "ebgames.com",
		"desc": "Games for Xbox 360, PS3, Wii, DS, 3DS, PS2, PSP, PC and more.",
		"link": "http://click.linksynergy.com/fs-bin/click?id=GU*lP9Glm/0&offerid=13850.10000167&type=3&subid=0",
		"img": "",
		"aff": true,
		"live": false
	},
	{
		"id": 91,
		"tags": [1],
		"name": "eBags",
    "domain": "",
		"desc": "Largest Online Retailer of Handbags, Luggage, Backpacks, and More.",
		"link": "http://www.kqzyfj.com/click-4147908-10293409",
		"img": "ebags.png",
		"aff": true,
		"live": true
	},
	{
		"id": 108,
		"tags": [1,4],
		"name": "Ecolissa",
    "domain": "",
		"desc": "Fashionable eco friendly and vegan womens clothing and accessories.",
		"link": "http://www.ecolissa.com/?Click=206",
		"img": "ecolissa.png",
		"aff": true,
		"live": true
	},
	{
		"id": 24,
		"tags": [1,4,17],
		"name": "Eddie Bauer",
    "domain": "",
		"desc": "Eddie Bauer is a premium outdoor retailer offering signature outerwear, clothing, shoes, accessories and world-class mountaineering gear for men and women.",
		"link": "http://gan.doubleclick.net/gan_click?lid=41000000000102581&pubid=21000000000316594",
		"img": "eddiebauer.png",
		"aff": true,
		"live": true
	},
	{
		"id": 69,
		"tags": [10],
		"name": "eHealth Insurance",
    "domain": "",
		"desc": "Free health insurance quotes online. Compare & buy medical insurance plans online in minutes.",
		"link": "http://www.jdoqocy.com/click-4147908-10496006",
		"img": "ehealth.png",
		"aff": true,
		"live": false
	},
	{
		"id": 115,
		"tags": [1],
		"name": "Endless",
    "domain": "",
		"desc": "A destination for shoes and handbags dedicated to providing the best prices, selection and overall experience, including free overnight shipping.",
		"link": "http://www.endless.com/?_encoding=UTF8&tag=pungle00-20&linkCode=ur2&camp=1789&creative=9325",
		"img": "endless.png",
		"aff": true,
		"live": true
	},
	{
		"id": 172,
		"tags": [10,11],
		"name": "Equita",
    "domain": "",
		"desc": "Fair trade, organic and green products for the body and home.",
		"link": "http://www.shopequita.com",
		"img": "equita.png",
		"aff": false,
		"live": true
	},
	{
		"id": 157,
		"tags": [11],
		"name": "Ethan Allen",
    "domain": "",
		"desc": "Modern, traditional and casual furniture.",
		"link": "http://www.ethanallen.com",
		"img": ".png",
		"aff": false,
		"live": false
	},
	{
		"id": 19,
		"tags": [18],
		"name": "Expedia",
    "domain": "",
		"desc": "Plan a trip, book cheap airfares, make hotel reservations, and find vacation packages, car rental & cruise deals.",
		"link": "http://www.tkqlhce.com/click-4147908-10514998",
		"img": "expedia.png",
		"aff": true,
		"live": true
	},
	{
		"id": 10,
		"tags": [4],
		"name": "Express",
    "domain": "",
		"desc": "Express is a sophisticated fashion brand for work, the weekend, or going out. It's what's new and what's now for young fashion-forward women and men.",
		"link": "http://gan.doubleclick.net/gan_click?lid=41000000027001271&pubid=21000000000316594",
		"img": "express.png",
		"aff": true,
		"live": true
	},
	{
		"id": 70,
		"tags": [8],
		"name": "Fabric.com",
    "domain": "",
		"desc": "Find fabric by the yard, from discount to designer and read sewing tips for inspiration.",
		"link": "http://www.dpbolvw.net/click-4147908-10283474?cm_mmc=CJ-_-3149226-_-4147908-_-Fabric.com",
		"img": "fabric.png",
		"aff": true,
		"live": true
	},
	{
		"id": 25,
		"tags": [1],
		"name": "Famous Footwear",
    "domain": "",
		"desc": "A great selection and low prices of women's shoes, men's shoes and kids' shoes with free in-store returns and exchanges!",
		"link": "http://gan.doubleclick.net/gan_click?lid=41000000026809670&pubid=21000000000316594",
		"img": "famoufootwear.png",
		"aff": true,
		"live": true
	},
	{
		"id": 167,
		"tags": [5],
		"name": "FedEx",
    "domain": "",
		"desc": "A complete suite of online services for shipments.",
		"link": "http://fedex.com/us",
		"img": "fedex.png",
		"aff": false,
		"live": true
	},
	{
		"id": 173,
		"tags": [19],
		"name": "Food Fight",
    "domain": "",
		"desc": "An all vegan grocery store. Independent. Mom and Pop-ish.",
		"link": "http://www.foodfightgrocery.com",
		"img": "foodfight.png",
		"aff": false,
		"live": true
	},
	{
		"id": 79,
		"tags": [1,4,17],
		"name": "Footlocker",
    "domain": "",
		"desc": "Foot Locker, Inc. is the world's leading retailer of athletic footwear, apparel and accessories.",
		"link": "http://click.linksynergy.com/fs-bin/click?id=GU*lP9Glm/0&offerid=203806.10000461&type=4&subid=0",
		"img": "footlocker.png",
		"aff": true,
		"live": true
	},
	{
		"id": 133,
		"tags": [1,4],
		"name": "Forever 21",
    "domain": "",
		"desc": "The most current fashions for women and men.",
		"link": "http://www.forever21.com",
		"img": "forever21.png",
		"aff": false,
		"live": true
	},
	{
		"id": 71,
		"tags": [1],
		"name": "Fossil",
    "domain": "",
		"desc": "Vintage Inspired Watches & Fashion Since 1984.",
		"link": "http://click.linksynergy.com/fs-bin/click?id=GU*lP9Glm/0&offerid=189453.10000022&type=4&subid=0",
		"img": "fossil.png",
		"aff": true,
		"live": true
	},
	{
		"id": 35,
		"tags": [1,10],
		"name": "Frederick's of Hollywood",
    "domain": "",
		"desc": "Lingerie is our heritage. Selling sexy bras, panties and more.",
		"link": "http://click.linksynergy.com/fs-bin/click?id=GU*lP9Glm/0&offerid=190736.10000009&subid=0&type=4",
		"img": "fredericks.png",
		"aff": true,
		"live": true
	},
	{
		"id": 72,
		"tags": [14],
		"name": "Gamefly",
    "domain": "",
		"desc": "Online video game rentals for all kinds of consoles, with cheats, hints, codes, reviews and more.",
		"link": "http://www.tkqlhce.com/click-4147908-10308499",
		"img": "gamefly.png",
		"aff": true,
		"live": true
	},
	{
		"id": 6,
		"tags": [14],
		"name": "Gamestop",
    "domain": "",
		"desc": "PlayStation 3, PS2, PSP, Nintendo Wii, DS, XBox, Xbox360, GameCube and PC Games.",
		"link": "http://click.linksynergy.com/fs-bin/click?id=GU*lP9Glm/0&offerid=121938.10000068&type=3&subid=0",
		"img": "gamestop.png",
		"aff": true,
		"live": true
	},
	{
		"id": 9,
		"tags": [1,4],
		"name": "Gap",
    "domain": "",
		"desc": "Clothes for the whole family. You'll find Petites and Tall sizes, kids slim and husky sizes, and baby bedding. You'll also find your favorite jeans, T-shirts and more.",
		"link": "http://www.kqzyfj.com/click-4147908-10415271",
		"img": "gap.png",
		"aff": true,
		"live": true
	},
	{
		"id": 73,
		"tags": [19],
		"name": "Ghiradelli",
    "domain": "",
		"desc": "Premium chocolate company incorporated since 1852.",
		"link": "http://www.dpbolvw.net/click-4147908-10691105",
		"img": "ghiradelli.png",
		"aff": true,
		"live": true
	},
	{
		"id": 134,
		"tags": [1,4,11],
		"name": "Gianna",
    "domain": "",
		"desc": "Fair trade gifts, eco-friendly and organic clothes, home decor and accessories handmade by disadvantaged women.",
		"link": "http://www.giannafairtrade.com",
		"img": "gianna.png",
		"aff": false,
		"live": true
	},
	{
		"id": 135,
		"tags": [1,4,20],
		"name": "Glamour Kills",
    "domain": "",
		"desc": "Girls and guys graphic tees and hoodies. Also carries jewelry, tote bags, posters and decals.",
		"link": "http://www.glamourkills.com",
		"img": "glamourkills.png",
		"aff": false,
		"live": true
	},
	{
		"id": 74,
		"tags": [12],
		"name": "Go Daddy",
    "domain": "",
		"desc": "Buy, manage & host websites for less, including ecommerce sites and easy-to-use site builders.",
		"link": "http://gan.doubleclick.net/gan_click?lid=41000000032103755&pubid=21000000000316594",
		"img": "godaddy.png",
		"aff": true,
		"live": true
	},
	{
		"id": 57,
		"tags": [11],
		"name": "The Great Indoors",
    "domain": "",
		"desc": "A huge selection of products specifically for decorating your home or accomplishing your home remodeling project. Founded in Denver, Colorado since 1998",
		"link": "http://gan.doubleclick.net/gan_click?lid=41000000023797989&pubid=21000000000316594",
		"img": "greatindoors.png",
		"aff": true,
		"live": true
	},
	{
		"id": 75,
		"tags": [19,9],
		"name": "Groupon",
    "domain": "",
		"desc": "Get 50 to 90 percent off the best stuff your city has to offer.",
		"link": "http://www.dpbolvw.net/click-4147908-10769812",
		"img": "groupon.png",
		"aff": true,
		"live": true
	},
	{
		"id": 116,
		"tags": [1,4],
		"name": "Guess",
    "domain": "",
		"desc": "Dress to impress with the latest styles in jeans, denim, tops, shirts, watches, shoes, jewelry, handbags & more.",
		"link": "http://shop.guess.com/",
		"img": ".png",
		"aff": false,
		"live": false
	},
	{
		"id": 92,
		"tags": [5],
		"name": "H&R Block",
    "domain": "",
		"desc": "Your single source for tax preparation.",
		"link": "http://www.jdoqocy.com/click-4147908-10460346",
		"img": "hrblock.png",
		"aff": true,
		"live": true
	},
	{
		"id": 109,
		"tags": [19],
		"name": "Happy Tiffin",
    "domain": "",
		"desc": "The premier 'green' food container company.",
		"link": "http://www.happytiffin.com/index.php?ref=12&cPath=0&affiliate_banner_id=12",
		"img": "happytiffin.png",
		"aff": true,
		"live": true
	},
	{
		"id": 76,
		"tags": [9,19],
		"name": "Harry & David",
    "domain": "",
		"desc": "Gourmet gift baskets, fresh fruit gifts, gourmet chocolate and Fruit-of-the-Month club, in the gift business for over 75 years.",
		"link": "http://www.kqzyfj.com/click-4147908-10788972",
		"img": "harryanddavid.png",
		"aff": true,
		"live": true
	},
	{
		"id": 176,
		"tags": [1,3,4,20],
		"name": "Herbivore Clothing Co",
    "domain": "",
		"desc": "Vegan clothing, books, stickers, purses, jewelry, accessories and more.",
		"link": "http://www.herbivoreclothing.com",
		"img": "herbivore.png",
		"aff": false,
		"live": true
	},
	{
		"id": 136,
		"tags": [11],
		"name": "The Home Depot",
    "domain": "",
		"desc": "All your home improvement needs.",
		"link": "http://www.homedepot.com",
		"img": "homedepot.png",
		"aff": false,
		"live": true
	},
	{
		"id": 20,
		"tags": [18],
		"name": "Hotels.com",
    "domain": "",
		"desc": "Choose from luxury to cheap, B&B to 5 star hotels. Read reviews, detailed descriptions, maps and quality photos. Now With No Change or Cancel Fees.",
		"link": "http://www.dpbolvw.net/click-4147908-10443216",
		"img": "hotels.png",
		"aff": true,
		"live": true
	},
	{
		"id": 34,
		"tags": [1,4],
		"name": "Hot Topic",
    "domain": "",
		"desc": "Hot Topic specializes in music and pop culture based fashion including Rock T-Shirts, Skinny Jeans, Band Tees, accessories and more.",
		"link": "http://www.anrdoezrs.net/click-4147908-10366692",
		"img": "hottopic.png",
		"aff": true,
		"live": true
	},
	{
		"id": 93,
		"tags": [5],
		"name": "HP Home",
    "domain": "",
		"desc": "HP laptops, notebooks, desktops, printers and more.",
		"link": "http://www.jdoqocy.com/click-4147908-10423984",
		"img": "hp.png",
		"aff": true,
		"live": true
	},
	{
		"id": 158,
		"tags": [1,4,10],
		"name": "ideeli",
    "domain": "",
		"desc": "Must-have brands from the worlds of fashion, home and beauty at up to 80% off.",
		"link": "http://www.ideeli.com",
		"img": "ideeli.png",
		"aff": false,
		"live": true
	},
	{
		"id": 4,
		"tags": [13],
		"name": "iTunes",
    "domain": "",
		"desc": "Get Your Favorite Songs & Movies Instantly from the iTunes Store.",
		"link": "http://click.linksynergy.com/fs-bin/click?id=GU*lP9Glm/0&offerid=146261.10000007&type=3&subid=0",
		"img": "itunes.png",
		"aff": true,
		"live": true
	},
	{
		"id": 138,
		"tags": [1,4,7],
		"name": "J.CREW",
    "domain": "",
		"desc": "Highest quality men's and women's clothing as well as children's clothing.",
		"link": "http://www.jcrew.com",
		"img": "jcrew.png",
		"aff": false,
		"live": true
	},
	{
		"id": 137,
		"tags": [1,4,7,10,11],
		"name": "JC Penny",
    "domain": "",
		"desc": "Apparel, shoes, jewelry, bedding, windows, and furniture. ",
		"link": "http://www.jcpenney.com",
		"img": "jcpenny.png",
		"aff": false,
		"live": true,
		"deals": [
		]
	},
	{
		"id": 95,
		"tags": [9],
		"name": "JibJab",
    "domain": "",
		"desc": "Funny eCards, birthday cards, and more.",
		"link": "http://www.dpbolvw.net/click-4147908-10686012",
		"img": "jibjab.png",
		"aff": true,
		"live": true
	},
	{
		"id": 121,
		"tags": [8],
		"name": "Joann",
    "domain": "",
		"desc": "Largest assortment of fabric, sewing, quilting, scrapbooking, knitting, crochet, Jewelry and other craft items.",
		"link": "http://www.joann.com",
		"img": ".png",
		"aff": false,
		"live": false
	},
	{
		"id": 30,
		"tags": [1,4],
		"name": "Journeys",
    "domain": "",
		"desc": "Journeys is your destination for funky, hip shoes & apparel.",
		"link": "http://gan.doubleclick.net/gan_click?lid=41000000011199806&pubid=21000000000316594",
		"img": "journeys.png",
		"aff": true,
		"live": true
	},
	{
		"id": 42,
		"tags": [1,20,3,4,5,6,7,19,9,10,11,13,15,16,17,8,14],
		"name": "Kmart",
    "domain": "",
		"desc": "Discount department store and online retailer since 1962 - Find The Products You Love at Prices You Deserve at Kmart.com",
		"link": "http://gan.doubleclick.net/gan_click?lid=41000000027619266&pubid=21000000000316594",
		"img": "kmart.png",
		"aff": true,
		"live": true
	},
	{
		"id": 33,
		"tags": [1,4,7,10,11,8,16],
		"name": "Kohl's",
    "domain": "",
		"desc": "Expect Great Things when you shop Kohl's for apparel, shoes, accessories, home products and more.",
		"link": "http://gan.doubleclick.net/gan_click?lid=41000000000387007&pubid=21000000000316594",
		"img": "kohls.png",
		"aff": true,
		"live": true
	},
	{
		"id": 139,
		"tags": [1,4],
		"name": "L.L.Bean",
    "domain": "",
		"desc": "Clothing and outdoor gear for the whole family.",
		"link": "http://www.llbean.com",
		"img": "llbean.png",
		"aff": false,
		"live": true
	},
	{
		"id": 94,
		"tags": [5],
		"name": "Lenovo",
    "domain": "",
		"desc": "Laptops, desktop, notebooks & netbooks.",
		"link": "http://www.jdoqocy.com/click-4147908-10484616",
		"img": "lenovo.png",
		"aff": true,
		"live": true
	},
	{
		"id": 43,
		"tags": [1],
		"name": "Lids",
    "domain": "",
		"desc": "Hats and caps for your favorite team or school in your favorite style.",
		"link": "http://www.kqzyfj.com/click-4147908-10429570",
		"img": "lids.png",
		"aff": true,
		"live": true
	},
	{
		"id": 150,
		"tags": [1,4],
		"name": "The Limited",
    "domain": "",
		"desc": "Quality fashion. Value pricing.",
		"link": "http://www.thelimited.com/",
		"img": ".png",
		"aff": false,
		"live": false
	},
	{
		"id": 44,
		"tags": [11],
		"name": "Linens n Things",
    "domain": "",
		"desc": "An online retailer of home textiles, housewares and decorative home accessories.",
		"link": "http://www.anrdoezrs.net/click-4147908-10809452",
		"img": "linensnthings.png",
		"aff": true,
		"live": true
	},
	{
		"id": 170,
		"tags": [9,19],
		"name": "LivingSocial",
    "domain": "",
		"desc": "Amazing Daily Deals 50-90% Off Restaurants, Spas, Events and More!",
		"link": "http://livingsocial.com",
		"img": "livingsocial.png",
		"aff": false,
		"live": true
	},
	{
		"id": 175,
		"tags": [4],
		"name": "loyale",
    "domain": "",
		"desc": "Celebrate organic luxury with our eco-friendly clothing.",
		"link": "http://www.loyaleclothing.com/shop.htm",
		"img": "loyale.png",
		"aff": false,
		"live": true
	},
	{
		"id": 101,
		"tags": [4],
		"name": "Lucky Brand",
    "domain": "",
		"desc": "Jeans, Men's & Women's Clothing & Designer Denim.",
		"link": "http://www.luckybrand.com/",
		"img": "luckybrand.png",
		"aff": false,
		"live": false
	},
	{
		"id": 7,
		"tags": [1,4,11],
		"name": "Macys",
    "domain": "",
		"desc": "Fashion Apparel and Accessories, Shoes, Perfume, Handbags, Bedding, Furniture, Mattresses, Small Kitchen Appliances and more.",
		"link": "http://click.linksynergy.com/fs-bin/click?id=GU*lP9Glm/0&offerid=206959.100218503&type=3&subid=0",
		"img": "macys.png",
		"aff": true,
		"live": true
	},
	{
		"id": 47,
		"tags": [1],
		"name": "Major League Baseball",
    "domain": "",
		"desc": "Major league baseball apparel and more.",
		"link": "http://www.gopjn.com/t/Sj9GSEtGP0dLSUdLP0ZLS0JF",
		"img": "mlb.png",
		"aff": true,
		"live": true
	},
	{
		"id": 102,
		"tags": [5],
		"name": "Microsoft Store",
    "domain": "",
		"desc": "Microsoft products, computers, games, downloads and more.",
		"link": "http://click.linksynergy.com/fs-bin/click?id=GU*lP9Glm/0&offerid=166833.10000490&type=3&subid=0",
		"img": "microsoft.png",
		"aff": true,
		"live": true
	},
	{
		"id": 174,
		"tags": [1],
		"name": "milk & honey",
    "domain": "",
		"desc": "Design and Create Your Own Custom Shoes, Bridal Shoes, Vegan/Vegetarian Eco Friendly shoes.",
		"link": "http://www.milkandhoneyshoes.com",
		"img": "milkandhoney.png",
		"aff": false,
		"live": true
	},
	{
		"id": 45,
		"tags": [5],
		"name": "Mint.com",
    "domain": "",
		"desc": "Free personal finance software to assist you to manage your money, financial planning, and budget planning tools. Achieve your financial goals with Mint.",
		"link": "http://www.tkqlhce.com/click-4147908-10780256",
		"img": "mint.png",
		"aff": true,
		"live": true
	},
	{
		"id": 140,
		"tags": [1,4,11],
		"name": "ModCloth",
    "domain": "",
		"desc": "Specialized in indie, retro, and vintage apparel, accessories, shoes, and decor from independent designers and artists.",
		"link": "http://www.anrdoezrs.net/click-4147908-10830756",
		"img": "modcloth.png",
		"aff": true,
		"live": true
	},
	{
		"id": 178,
		"tags": [1],
		"name": "MooShoes",
    "domain": "",
		"desc": "Synthetic sneakers and non-leather shoes, belts and accessories.",
		"link": "http://www.mooshoes.com",
		"img": "mooshoes.png",
		"aff": false,
		"live": true
	},
	{
		"id": 46,
		"tags": [2],
		"name": "Motorcycle Superstore",
    "domain": "",
		"desc": "Largest online motorcycle accessory store selling motorcycle gear, apparel, tires and more.",
		"link": "http://www.anrdoezrs.net/click-4147908-10562949",
		"img": "motorcyclesuperstore.png",
		"aff": true,
		"live": true
	},
	{
		"id": 13,
		"tags": [6,13,20,8],
		"name": "Musician's Friend",
    "domain": "",
		"desc": "The hottest music gear at the lowest prices since 1983.",
		"link": "http://www.dpbolvw.net/click-4147908-10451188",
		"img": "musiciansfriend.png",
		"aff": true,
		"live": true
	},
	{
		"id": 103,
		"tags": [13,8],
		"name": "MusicNotes",
    "domain": "",
		"desc": "Instantly download sheet music and guitar tab from the largest catalog of official and licensed digital sheet music.",
		"link": "http://click.linksynergy.com/fs-bin/click?id=GU*lP9Glm/0&offerid=90283.10000007&type=3&subid=0",
		"img": "musicnotes.png",
		"aff": true,
		"live": true
	},
	{
		"id": 110,
		"tags": [4],
		"name": "Need Supply Co",
    "domain": "",
		"desc": "Eclectic mix of hard-to-find vintage apparel to a well-edited selection of premium street wear and contemporary brands.",
		"link": "http://needsupply.com?a=97",
		"img": "needsupplyco.png",
		"aff": true,
		"live": true
	},
	{
		"id": 5,
		"tags": [5,6,20,8,14],
		"name": "Newegg",
    "domain": "",
		"desc": "Computer products, laptops, TVs, digital cameras, electronics, unlocked phones, office supplies, and more with fast shipping and top-rated customer service.",
		"link": "http://www.jdoqocy.com/click-4147908-10444948",
		"img": "newegg.png",
		"aff": true,
		"live": true
	},
	{
		"id": 104,
		"tags": [1,4],
		"name": "NFL Shop",
    "domain": "",
		"desc": "Wide selection of Official NFL gear, apparel and jerseys.",
		"link": "http://www.pntrac.com/t/Sj9GSkJCP0dLSUdLP0dDREtH",
		"img": "nfl.png",
		"aff": true,
		"live": true
	},
	{
		"id": 141,
		"tags": [1,4,10,7],
		"name": "Nordstrom",
    "domain": "",
		"desc": "Designer apparel, shoes, jewelry, cosmetics, fragrances and accessories for women, men and kids.",
		"link": "http://shop.nordstrom.com",
		"img": "nordstrom.png",
		"aff": false,
		"live": true
	},
	{
		"id": 165,
		"tags": [1],
		"name": "Oddball",
    "domain": "",
		"desc": "Large size men's shoes in top brands up to 6E in width.",
		"link": "http://www.oddball.com",
		"img": "oddball.png",
		"aff": false,
		"live": true
	},
	{
		"id": 81,
		"tags": [5],
		"name": "Office Depot",
    "domain": "",
		"desc": "If you're looking for office supplies, the name says it all.",
		"link": "http://click.linksynergy.com/fs-bin/click?id=GU*lP9Glm/0&offerid=174585.10000576&subid=0&type=4",
		"img": "officedepot.png",
		"aff": true,
		"live": true
	},
	{
		"id": 105,
		"tags": [5],
		"name": "OfficeMax",
    "domain": "",
		"desc": "The office-manager friendly choice for office supplies, office furniture and all types of office technology.",
		"link": "http://gan.doubleclick.net/gan_click?lid=41000000029742007&pubid=21000000000316594",
		"img": "officemax.png",
		"aff": true,
		"live": true
	},
	{
		"id": 151,
		"tags": [4,7],
		"name": "Old Navy",
    "domain": "",
		"desc": "The latest fashions at great prices for the whole family.",
		"link": "http://www.kqzyfj.com/click-4147908-10415271",
		"img": "oldnavy.png",
		"aff": true,
		"live": true
	},
	{
		"id": 82,
		"tags": [19],
		"name": "Omaha Steaks",
    "domain": "",
		"desc": "Premium steaks, red meats and other gourmet foods.",
		"link": "http://click.linksynergy.com/fs-bin/click?id=GU*lP9Glm/0&offerid=214803.10000037&type=3&subid=0",
		"img": "omahasteaks.png",
		"aff": true,
		"live": true
	},
	{
		"id": 48,
		"tags": [18],
		"name": "Orbitz",
    "domain": "",
		"desc": "Book cheap airline tickets, hotel reservations, car rentals, vacations and travel deals.",
		"link": "http://click.linksynergy.com/fs-bin/click?id=GU*lP9Glm/0&offerid=191979.10001373&subid=0&type=4",
		"img": "orbitz.png",
		"aff": true,
		"live": true
	},
	{
		"id": 127,
		"tags": [9,8,20],
		"name": "Oriental Trading Company",
    "domain": "",
		"desc": "An irresistible assortment of fun, value-priced products for every occasion.",
		"link": "http://www.orientaltrading.com",
		"img": ".png",
		"aff": false,
		"live": false
	},
	{
		"id": 49,
		"tags": [17],
		"name": "Orvis",
    "domain": "",
		"desc": "A family-owned business specializing in high-end fly fishing, hunting and sporting goods. Founded in Manchester, Vermont.",
		"link": "http://gan.doubleclick.net/gan_click?lid=41000000030313138&pubid=21000000000316594",
		"img": "orvis.png",
		"aff": true,
		"live": true
	},
	{
		"id": 3,
		"tags": [1,4,5,6,7,9,10,11,13,16,17,8,14,15],
		"name": "Overstock",
    "domain": "",
		"desc": "Buy discounted brand Bedding, Furniture, Jewelry, Watches, Electronics, Clothing, Books, Movies, and Music for the lowest prices every day.",
		"link": "http://www.kqzyfj.com/click-4147908-10653482",
		"img": "overstock.png",
		"aff": true,
		"live": true
	},
	{
		"id": 32,
		"tags": [1],
		"name": "Pacsun",
    "domain": "",
		"desc": "Shop the hottest girls clothes, guys clothes & accessories. Get the latest looks in casual teen apparel by top girls & guys clothing brands.",
		"link": "http://www.kqzyfj.com/click-4147908-9832459",
		"img": "pacsun.png",
		"aff": true,
		"live": true
	},
	{
		"id": 142,
		"tags": [4],
		"name": "PACT",
    "domain": "",
		"desc": "Design-driven, responsibly manufactured,premium organic cotton underwear connected to powerful social and environmental causes.",
		"link": "http://www.wearpact.com",
		"img": "pact.png",
		"aff": false,
		"live": true
	},
	{
		"id": 181,
		"tags": [4],
		"name": "Paul Fredrick",
    "domain": "",
		"desc": "Paul Fredrick's men's clothing offers the discerning man a one stop for men's suits, pants and more.",
		"link": "http://click.linksynergy.com/fs-bin/click?id=GU*lP9Glm/0&offerid=143866.9&type=3&subid=0",
		"img": "",
		"aff": true,
		"live": false
	},
	{
		"id": 16,
		"tags": [15],
		"name": "Petsmart",
    "domain": "",
		"desc": "PetSmart offers the best pet supplies, services, and expertise to help you care for your pets.",
		"link": "http://click.linksynergy.com/fs-bin/click?id=GU*lP9Glm/0&offerid=174251.10000063&type=4&subid=0",
		"img": "petsmart.png",
		"aff": true,
		"live": true
	},
	{
		"id": 153,
		"tags": [1,4],
		"name": "Piperlime",
    "domain": "",
		"desc": "Women's shoes, handbags, apparel, and jewelry.",
		"link": "http://www.kqzyfj.com/click-4147908-10415271",
		"img": "piperlime.png",
		"aff": true,
		"live": true
	},
	{
		"id": 96,
		"tags": [1],
		"name": "Planet Shoes",
    "domain": "",
		"desc": "Home of Earth Footwear, Blowfish Shoes, Vegan Shoes and an amazing selection of Eco-Friendly Shoes.",
		"link": "http://www.anrdoezrs.net/click-4147908-10558106",
		"img": "planetshoes.png",
		"aff": true,
		"live": true
	},
	{
		"id": 143,
		"tags": [11],
		"name": "Pottery Barn",
    "domain": "",
		"desc": "Expertly crafted home furnishings and home decor.",
		"link": "http://www.potterybarn.com",
		"img": "potterybarn.png",
		"aff": false,
		"live": true
	},
	{
		"id": 18,
		"tags": [18],
		"name": "Priceline",
    "domain": "",
		"desc": "Get deep discounts on flights, hotels, rental cars, vacations and cruises. Exclusive travel discounts you won't find anywhere else.",
		"link": "http://www.anrdoezrs.net/click-4147908-10392991",
		"img": "priceline.png",
		"aff": true,
		"live": true
	},
	{
		"id": 50,
		"tags": [9],
		"name": "Pro Flowers",
    "domain": "",
		"desc": "Order flowers online with nationwide flower delivery.",
		"link": "http://gan.doubleclick.net/gan_click?lid=41000000028437763&pubid=21000000000316594",
		"img": "proflowers.png",
		"aff": true,
		"live": true
	},
	{
		"id": 26,
		"tags": [1],
		"name": "Puma",
    "domain": "",
		"desc": "A German shoe, sportswear and lifestyle company since 1924",
		"link": "http://gan.doubleclick.net/gan_click?lid=41000000032595827&pubid=21000000000316594",
		"img": "puma.png",
		"aff": true,
		"live": true
	},
	{
		"id": 171,
		"tags": [12],
		"name": "Rackspace",
    "domain": "",
		"desc": "Cloud computing and cloud hosting powered by Rackspace Cloud computing.",
		"link": "http://www.rackspacecloud.com/2029.html",
		"img": "rackspace.png",
		"aff": true,
		"live": true
	},
	{
		"id": 51,
		"tags": [18],
		"name": "Rail Europe",
    "domain": "",
		"desc": "Europe Train Tickets, Reservations, Unlimited Rail Passes, Maps & More.",
		"link": "",
		"img": "raileurope.png",
		"aff": true,
		"live": false
	},
	{
		"id": 180,
		"tags": [1,4,17],
		"name": "REI",
    "domain": "",
		"desc": "Great gear, equipment and clothing you need for outdoor adventures.",
		"link": "http://www.rei.com",
		"img": ".png",
		"aff": false,
		"live": false
	},
	{
		"id": 156,
		"tags": [20],
		"name": "Ritz Camera",
    "domain": "",
		"desc": "Digital cameras, electronics and more.",
		"link": "http://www.jdoqocy.com/click-4147908-10715319",
		"img": "ritzcamera.png",
		"aff": true,
		"live": true
	},
	{
		"id": 52,
		"tags": [1],
		"name": "Road Runner Sports",
    "domain": "",
		"desc": "Road Runner Sports is the World's Largest Running Store.",
		"link": "http://gan.doubleclick.net/gan_click?lid=41000000000425997&pubid=21000000000316594",
		"img": "roadrunner.png",
		"aff": true,
		"live": true
	},
	{
		"id": 11,
		"tags": [1,20,2,3,4,5,6,7,10,11,13,16,8,14],
		"name": "Sears",
    "domain": "",
		"desc": "Great selection and value for your home and family including tools, appliances, tires, mowers, electronics, and much more.",
		"link": "http://gan.doubleclick.net/gan_click?lid=41000000028682458&pubid=21000000000316594",
		"img": "sears.png",
		"aff": true,
		"live": true
	},
	{
		"id": 36,
		"tags": [10],
		"name": "Sephora",
    "domain": "",
		"desc": "Sephora.com is a leading beauty retailer offering the best cosmetics, skin care, makeup, fragrance & perfume, hair, beauty products and makeup tips.",
		"link": "http://click.linksynergy.com/fs-bin/click?id=GU*lP9Glm/0&offerid=32532.10000186&type=4&subid=0",
		"img": "sephora.png",
		"aff": true,
		"live": true
	},
	{
		"id": 97,
		"tags": [1,4],
		"name": "Shopbop",
    "domain": "",
		"desc": "Designer women's fashion brands.",
		"link": "http://www.anrdoezrs.net/click-4147908-10522668",
		"img": "shopbop.png",
		"aff": true,
		"live": true
	},
	{
		"id": 28,
		"tags": [1],
		"name": "Skechers",
    "domain": "",
		"desc": "Makers of athletic, dress, casual and work shoes for Women, Men and Kids.",
		"link": "http://www.dpbolvw.net/click-4147908-10662742",
		"img": "skechers.png",
		"aff": true,
		"live": true
	},
	{
		"id": 53,
		"tags": [20],
		"name": "Snapfish",
    "domain": "",
		"desc": "Snapfish is a web-based photo sharing and photo printing service that offers cards, photos, gifts and more.",
		"link": "http://www.tkqlhce.com/click-4147908-10836374",
		"img": "snapfish.png",
		"aff": true,
		"live": true
	},
	{
		"id": 54,
		"tags": [10],
		"name": "Soap.com",
    "domain": "",
		"desc": "Offers Health, Beauty & Household Essentials with 24/7 customer service, free shipping and a 365-day return policy.",
		"link": "http://gan.doubleclick.net/gan_click?lid=41000000032029712&pubid=21000000000316594",
		"img": "soap.png",
		"aff": true,
		"live": true
	},
	{
		"id": 120,
		"tags": [5,6,14],
		"name": "Sony",
    "domain": "",
		"desc": "Sony computers, electronics, playstation, games and more.",
		"link": "http://www.sony.com/index.php",
		"img": ".png",
		"aff": false,
		"live": false
	},
	{
		"id": 23,
		"tags": [17],
		"name": "Sports Authority",
    "domain": "",
		"desc": "Sports Authority - the nation's preeminent full-line sporting goods chain. Shop for your favorite brands",
		"link": "http://www.pntra.com/t/Sj9GSUtLP0dLSUdLP0dDREtE",
		"img": "sportsauthority.png",
		"aff": true,
		"live": true
	},
	{
		"id": 144,
		"tags": [4],
		"name": "Spun",
    "domain": "",
		"desc": "Sustainable women's fashion.",
		"link": "http://www.choosespun.com",
		"img": "spun.png",
		"aff": false,
		"live": true,
		"deals": [
		]
	},
	{
		"id": 119,
		"tags": [1],
		"name": "Steve Madden",
    "domain": "",
		"desc": "Shoes, sandals, boots, handbags, accessories and more.",
		"link": "http://www.stevemadden.com/",
		"img": ".png",
		"aff": false,
		"live": false
	},
	{
		"id": 55,
		"tags": [1,17],
		"name": "Sun Diego",
    "domain": "",
		"desc": "Offers surf, skate, and snowboarding products and accessories. Founded in San Diego, California.",
		"link": "http://gan.doubleclick.net/gan_click?lid=41000000027280222&pubid=21000000000316594",
		"img": "sundiego.png",
		"aff": true,
		"live": true
	},
	{
		"id": 159,
		"tags": [20,6,13,8],
		"name": "Sweetwater",
    "domain": "",
		"desc": "World's leading music technology and instrument retailer.",
		"link": "http://www.sweetwater.com",
		"img": "sweetwater.png",
		"aff": false,
		"live": true
	},
	{
		"id": 145,
		"tags": [1,4],
		"name": "Talbots",
    "domain": "",
		"desc": "Women's clothing, swimwear, suits, and accessories with a modern twist.",
		"link": "http://www.talbots.com",
		"img": "talbots.png",
		"aff": false,
		"live": true
	},
	{
		"id": 14,
		"tags": [1,2,3,4,5,6,7,19,9,10,11,13,15,16,17,8,14],
		"name": "Target",
    "domain": "",
		"desc": "An American retailer with over 800,000 items for sale online - Founded in 1902.",
		"link": "http://gan.doubleclick.net/gan_click?lid=41000000027328188&pubid=21000000000316594",
		"img": "target.png",
		"aff": true,
		"live": true
	},
	{
		"id": 162,
		"tags": [19,9],
		"name": "Tasting Room",
    "domain": "",
		"desc": "Taste wines before deciding to buy in the comfort of your home with exclusive wine samplers.",
		"link": "http://www.tastingroom.com",
		"img": "tastingroom.png",
		"aff": false,
		"live": true
	},
	{
		"id": 56,
		"tags": [3],
		"name": "Textbooks.com",
    "domain": "",
		"desc": "Browse the largest selection of new and used textbooks online, rent textbooks or sell your college textbooks online",
		"link": "http://gan.doubleclick.net/gan_click?lid=41000000028368621&pubid=21000000000316594",
		"img": "textbooks.png",
		"aff": true,
		"live": false
	},
	{
		"id": 114,
		"tags": [3,4,6,9,8],
		"name": "ThinkGeek",
    "domain": "",
		"desc": "Stuff for smart masses.",
		"link": "http://www.tkqlhce.com/click-4147908-10784884",
		"img": "thinkgeek.png",
		"aff": true,
		"live": true
	},
	{
		"id": 117,
		"tags": [4],
		"name": "Threadless",
    "domain": "",
		"desc": "The best tees on the planet.",
		"link": "http://www.threadless.com/",
		"img": ".png",
		"aff": false,
		"live": false
	},
	{
		"id": 58,
		"tags": [5,6,14],
		"name": "Tiger Direct",
    "domain": "",
		"desc": "Serving PC and electronics enthusiasts for over 20 years.",
		"link": "http://click.linksynergy.com/fs-bin/click?id=GU*lP9Glm/0&offerid=102327.10000077&type=4&subid=0",
		"img": "tigerdirect.png",
		"aff": true,
		"live": true
	},
	{
		"id": 31,
		"tags": [1,4],
		"name": "Tillys",
    "domain": "",
		"desc": "Shop the Latest Surf and Skate Clothing, Shoes and Accessories. Founded in 1982.",
		"link": "http://www.kqzyfj.com/click-4147908-10460352",
		"img": "tillys.png",
		"aff": true,
		"live": true
	},
	{
		"id": 15,
		"tags": [2],
		"name": "Tire Rack",
    "domain": "",
		"desc": "Great selection of wheels & tires online! Research and preview wheels on your car. Package deals delivered to your door.",
		"link": "http://www.jdoqocy.com/click-4147908-10376887",
		"img": "tirerack.png",
		"aff": true,
		"live": true
	},
	{
		"id": 29,
		"tags": [1],
		"name": "Tom's Shoes",
    "domain": "",
		"desc": "Shoe makers founded on a simple premise: For every pair you purchase, TOMS will give a pair of shoes to a child in need. One for One.",
		"link": "http://www.toms.com/",
		"img": "toms.png",
		"aff": false,
		"live": true
	},
	{
		"id": 59,
		"tags": [6,8,7],
		"name": "Toys R Us",
    "domain": "",
		"desc": "Leading online retailer for kids toys.",
		"link": "http://www.toysrus.com/",
		"img": "toysrus.png",
		"aff": false,
		"live": true
	},
	{
		"id": 12,
		"tags": [18],
		"name": "Travelocity",
    "domain": "",
		"desc": "Offers a variety of travel services, including fare finder, hotel and car rental information, reservations and destination information.",
		"link": "http://www.tkqlhce.com/click-4147908-10395449",
		"img": "travelocity.png",
		"aff": true,
		"live": true
	},
	{
		"id": 98,
		"tags": [5],
		"name": "TurboTax",
    "domain": "",
		"desc": "#1-rated, best-selling tax software.",
		"link": "http://www.jdoqocy.com/click-4147908-10458883",
		"img": "turbotax.png",
		"aff": true,
		"live": true
	},
	{
		"id": 169,
		"tags": [5],
		"name": "Uline",
    "domain": "",
		"desc": "Shipping boxes, packing materials and mailing supplies.",
		"link": "http://www.uline.com",
		"img": "uline.png",
		"aff": false,
		"live": true
	},
	{
		"id": 113,
		"tags": [1,7,9,11],
		"name": "Uncommon Goods",
    "domain": "",
		"desc": "Creative, eco-friendly gifts for birthdays, weddings, baby showers, anniversaries and more.",
		"link": "http://click.linksynergy.com/fs-bin/click?id=GU*lP9Glm/0&offerid=54404.10000243&type=3&subid=0",
		"img": "uncommongoods.png",
		"aff": true,
		"live": true
	},
	{
		"id": 166,
		"tags": [4],
		"name": "UNIQLO",
    "domain": "",
		"desc": "A new-style Japanese firm making good casual clothes available for all to wear.",
		"link": "http://www.uniqlo.com/us/",
		"img": "uniqlo.png",
		"aff": false,
		"live": true
	},
	{
		"id": 168,
		"tags": [5],
		"name": "UPS",
    "domain": "",
		"desc": "Shipping, Freight, Logistics and Supply Chain Management.",
		"link": "http://www.ups.com/us",
		"img": "ups.png",
		"aff": false,
		"live": true
	},
	{
		"id": 118,
		"tags": [1,4,11],
		"name": "Urban Outfitters",
    "domain": "",
		"desc": "Clothing, accessories, and apartment wares for young women and men.",
		"link": "http://www.urbanoutfitters.com",
		"img": ".png",
		"aff": false,
		"live": false
	},
	{
		"id": 146,
		"tags": [4],
		"name": "Vaute Couture",
    "domain": "",
		"desc": "A renegade fashion house that creates fabulous vegan coats.",
		"link": "http://www.vautecouture.com/t-shop.aspx",
		"img": "vautecouture.png",
		"aff": false,
		"live": true
	},
	{
		"id": 177,
		"tags": [1,4,7,10,19,15],
		"name": "Vegan Essentials",
    "domain": "",
		"desc": "Complete online vegan store for all your vegan products.",
		"link": "http://www.veganessentials.com",
		"img": "veganessentials.png",
		"aff": false,
		"live": true
	},
	{
		"id": 125,
		"tags": [4,10],
		"name": "Victoria's Secret",
    "domain": "",
		"desc": "The world's most glamorous lingerie. Chic women's clothing, sultry swimwear, and more.",
		"link": "http://www.victoriassecret.com",
		"img": "victoriasecret.png",
		"aff": false,
		"live": true
	},
	{
		"id": 60,
		"tags": [20],
		"name": "Vista Print",
    "domain": "",
		"desc": "Custom low-price full color printing services inlcuding free online design tools.",
		"link": "http://www.kqzyfj.com/click-4147908-10389462",
		"img": "vistaprint.png",
		"aff": true,
		"live": true
	},
	{
		"id": 2,
		"tags": [1,20,2,3,4,5,6,7,19,9,10,11,13,15,16,17,8,14],
		"name": "Walmart",
    "domain": "",
		"desc": "Electronics, home furnishings, video games, baby gear and more.",
		"link": "http://linksynergy.walmart.com/fs-bin/click?id=GU*lP9Glm/0&offerid=183959.10005617&type=3&subid=0",
		"img": "walmart.png",
		"aff": true,
		"live": true
	},
	{
		"id": 107,
		"tags": [1,4],
		"name": "WomanWithin",
    "domain": "",
		"desc": "A complete line of casual wear for the plus size woman.",
		"link": "http://gan.doubleclick.net/gan_click?lid=41000000015054384&pubid=21000000000316594",
		"img": "womanwithin.png",
		"aff": true,
		"live": true
	},
	{
		"id": 147,
		"tags": [11,19],
		"name": "Williams-Sonoma",
    "domain": "",
		"desc": "Gourmet foods, professional-quality cookware and kitchen decor.",
		"link": "http://www.williams-sonoma.com",
		"img": "williamssonoma.png",
		"aff": false,
		"live": true
	},
	{
		"id": 148,
		"tags": [19],
		"name": "Wine Library",
    "domain": "",
		"desc": "Awesome online wine store. Home of WineLibrary TV's Gary Vaynerchuk.",
		"link": "http://winelibrary.com/",
		"img": "winelibrary.png",
		"aff": false,
		"live": true
	},
	{
		"id": 80,
		"tags": [19],
		"name": "wine.com",
    "domain": "",
		"desc": "Easily find and ship the right wine at the #1 rated online wine store.",
		"link": "http://click.linksynergy.com/fs-bin/click?id=GU*lP9Glm/0&offerid=212891.10000769&type=4&subid=0",
		"img": "wine.png",
		"aff": true,
		"live": true
	},
	{
		"id": 38,
		"tags": [10],
		"name": "Yves Rocher",
    "domain": "",
		"desc": "Formed in France, Yves Rocher is a producer of natural beauty products and cosmetics",
		"link": "http://www.dpbolvw.net/click-4147908-10770769",
		"img": "yvesrocher.png",
		"aff": true,
		"live": true
	},
	{
		"id": 1,
		"tags": [1],
		"name": "Zappos",
    "domain": "zappos.com",
		"desc": "Free next day shipping on shoes, clothing, and more! 365-day return policy, over 1000 brands, 24/7 friendly customer service.",
		"link": "http://www.zappos.com",
		"img": "zappos.png",
		"aff": false,
		"live": true
	},
	{
		"id": 61,
		"tags": [1,4],
		"name": "Zazzle",
    "domain": "",
		"desc": "Create your own custom shirts, prints, mugs and more",
		"link": "http://gan.doubleclick.net/gan_click?lid=41000000030935412&pubid=21000000000316594",
		"img": "zazzle.png",
		"aff": true,
		"live": true
	}
]}
